//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC.models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int IdCliente { get; set; }
        public string AliasCliente { get; set; }
        public string NomCliente { get; set; }
        public string DirCliente { get; set; }
        public Nullable<int> idPais { get; set; }
        public string fonoCliente { get; set; }
    
        public virtual paises paises { get; set; }
    }
}
